# Generated by Django 4.1 on 2022-11-23 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='language',
            field=models.IntegerField(choices=[(1, 'Python'), (2, 'Java'), (3, 'JavaScript'), (4, 'C++'), (5, 'C')]),
        ),
    ]
